name: 📜 Docs

on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: RVrPO7a5oXq0ZnUd1-eDMubwWnI6yEAVA1dgKiNF

jobs:
  docs:
    name: "📜 Deploy Docs"

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run docs:build

      - run: npx wrangler publish
